baseurl = "https://michelemucci.net"
copyright = "© Michele Mucci"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "Europe/Berlin"
titlecasestyle = "Go"

[languages.en]
title = "Michele Mucci"
weight = 10

[[languages.en.menu.main]]
identifier = "info"
name = "Info"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "clients"
name = "Clients & Labels"
url = "#clients"
weight = 30

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "#contact"
weight = 40

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false


[paige]
color = "#00aidef" # Bootstrap primary color and theme color for Safari and Windows
external_link_new_tab = false # Open external links in new tabs
math = false # Enable math typesetting
style = "" # CSS included at the end of the stylesheet, before style-last.css


[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]


